import offline_rl.locomotion
import offline_rl.hand_manipulation_suite
import offline_rl.pointmaze
import offline_rl.gym_minigrid
import offline_rl.gym_mujoco
from offline_rl.offline_env import set_dataset_path
